-- AlterTable
ALTER TABLE "Contract" ALTER COLUMN "contractValue" SET DATA TYPE DECIMAL(20,2),
ALTER COLUMN "refundAmount" SET DATA TYPE DECIMAL(20,2),
ALTER COLUMN "executedValue" SET DATA TYPE DECIMAL(20,2);
